---
# Glib2 settings for a better user experience

- name: Disabling user listings in Metacity menu
  copy:
    src: com.canonical.indicator.session.gschema.override
    dest: /usr/share/glib-2.0/schemas/com.canonical.indicator.session.gschema.override
    backup: yes
  register: cfg_glib_users

- name:  Setting system proxy
  copy:
    src: org.gnome.system.proxy.gschema.override
    dest: /usr/share/glib-2.0/schemas/org.gnome.system.proxy.gschema.override
  register: cfg_glib_proxy

- name: Visualizing mounted drives on desktop
  copy:
    src: org.gnome.nautilus.desktop.gschema.override
    dest: /usr/share/glib-2.0/schemas/org.gnome.nautilus.desktop.gschema.override
    backup: yes
  register: cfg_glib_mounted

- name: Fixing keyboard layout
  copy:
    src: org.freedesktop.ibus.general.gschema.override
    dest: /usr/share/glib-2.0/schemas/org.freedesktop.ibus.general.schema.override
    backup: yes
  register: cfg_keyb_layout

- name: Recompiling glib2 schemas
  shell: glib-compile-schemas --strict /usr/share/glib-2.0/schemas/
  sudo: yes
  when: cfg_glib_proxy|changed or cfg_glib_users|changed or cfg_glib_mounted|changed or cfg_keyb_layout|changed
